name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]
    
env:
  filebuild: ./app/build/outputs/apk/debug/app-debug.apk
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Setting JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: memberikan Perizinan gradlew
      run: chmod +x gradlew
      
    - name: Build debug Apk
      run: bash ./gradlew assembleDebug --stacktrace
      
    - name: Upload Ke dalam Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
          name: 4LayT3xt
          path: $filebuild
    
    - name: Upload Release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      with:
        file: $filebuild
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        tags: true
        draft: true
      
