name: release

on:
  workflow_call:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: xresloader/upload-to-github-release@v1
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default_release_name: 4LayT3xt
          branches: "main"
          file: "./app/build/outputs/apk/debug/app-debug.apk"
