name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: 
      - uses: xresloader/upload-to-github-release@v1
        with:
          default_release_name: 4LayT3xt
          branches: "main"
          file: "./app/build/outputs/apk/debug/app-debug.apk"
